name: Playwright Tests
on:
  workflow_dispatch:
    inputs:
      stage_url:
        description: 'Select an environment: "dev" , "local"'
        required: true
        default: "https://backoffice-dev.eu.ballerine.io"
      qase_report:
        description: 'Choose qase report option: on(1) / off(0)'
        required: false
        default: "0"
      trace:
        type: choice
        description: 'Choose trace option: on / off / retain-on-failure'
        required: false
        default: "retain-on-failure"
        options:
          - "retain-on-failure"
          - "on"
          - "off"
      login:
        description: 'Set login option: default or custom'
        required: true
        default: "admin@admin.com"
      password:
        description: 'Set password option: default or custom'
        required: true
        default: "admin"

jobs:
  Run_tests:
    timeout-minutes: 300
    runs-on: ubuntu-latest
    container: 
      image: mcr.microsoft.com/playwright:v1.34.3-jammy
    env:
      STAGE_URL: ${{ inputs.stage_url }}
      QASE_REPORT: ${{ inputs.qase_report }}
      TRACE: ${{ inputs.trace }}
      LOGIN: ${{ inputs.login }}
      PASSWORD: ${{ inputs.password }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          npm i
          npx playwright install --with-deps
      - name: Run tests
        run: export BASE_URL="$STAGE_URL" LOGIN_EMAIL="$LOGIN" LOGIN_PASSWORD="$PASSWORD" && npx playwright test --trace "$TRACE"
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 5
