name: 'playwright'
on:
  workflow_dispatch:
    inputs:
      stage_url:
        description: 'Select an environment: "dev" , "local"'
        required: true
        default: "https://backoffice-dev.eu.ballerine.io"
      qase_report:
        description: 'Choose qase report option: on(1) / off(0)'
        required: false
        default: "0"
      trace:
        type: choice
        description: 'Choose trace option: on / off / retain-on-failure'
        required: false
        default: "retain-on-failure"
        options:
          - "retain-on-failure"
          - "on"
          - "off"
      login:
        description: 'Set login option: default or custom'
        required: true
        default: "admin@admin.com"
      password:
        description: 'Set password option: default or custom'
        required: true
        default: "admin"
      api_token_github:
        description: 'GitHub token'
        required: true
        default: ""
jobs:
    playwright:
        runs-on: ubuntu-latest
        env:
          STAGE_URL: ${{ inputs.stage_url }}
          QASE_REPORT: ${{ inputs.qase_report }}
          TRACE: ${{ inputs.trace }}
          LOGIN: ${{ inputs.login }}
          PASSWORD: ${{ inputs.password }}
          API_TOKEN_GITHUB: ${{ inputs.api_token_github }}
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        steps:
            - uses: actions/checkout@v1
            - uses: sidharthv96/playwright-report-action
              with:
                  github-token: ${{ env.API_TOKEN_GITHUB }}