run-name: Playwright tests =>branch - "${{ github.ref_name }}", env -"${{ inputs.environment_version }}",  customer - "${{ inputs.customer_company }}".

on:
  workflow_dispatch:
    inputs:
      environment_version:
        type: choice
        description: "Choose env"
        required: false
        default: "test"
        options:
          - "local"
          - "test"
      customer_company:
        type: choice
        description: "Choose customer company like clipspay or oxpay"
        required: false
        default: "OXPAY"
        options:
          - "CLIPSPAY"
          - "OXPAY"

jobs:
  Run_tests:
    timeout-minutes: 60
    runs-on: ubuntu-20.04
    environment: ${{ inputs.environment_version }}
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    env:
      COMPANY_MAP: '{"CLIPSPAY":"CLIPSPAY_COMPANY", "OXPAY":"OXPAY_COMPANY"}'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Set dynamic variable
        id: set_var
        run: |
          if [ "${{ inputs.customer_company }}" == "CLIPSPAY" ]; then
            echo "COMPANY=${{ vars.CLIPSPAY_COMPANY }}" >> $GITHUB_ENV
          elif [ "${{ inputs.customer_company }}" == "OXPAY" ]; then
            echo "COMPANY=${{ vars.OXPAY_COMPANY }}" >> $GITHUB_ENV
          fi

      - name: Print selected company
        run: echo "Selected Company $COMPANY"